language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install pybuilder coverage

script:
  - pyb --debug --verbose run_unit_tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
