language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pybuilder coverage
  - pip list installed

script:
  - pyb --environment ci --debug --verbose analyze run_unit_tests install
